### ISSUE TITLE
Consider Docker-based Thrift build

### ISSUE THREAD

**Issue by jparise** [pinterest/elixir-thrift#16]
The bulk of our CI (Travis) build time is spent (re)building the thrift compiler tool. (There unfortunately isn't a readily available Thrift 0.9.3 .deb package.)

Consider using a Docker-based build package like in dantswain/thrash#8.

**Comment by dantswain** [comment]
If you're interested, I could probably make a PR for this.

**Comment by jparise** [comment]
That would be great, @dantswain!

**Comment by jparise** [comment]
Closed by #24
