### ISSUE TITLE
It's possible to generate field names that do not compile as valid elixir

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#161]
Our team tends to deprecated thrift fields by prepending `DEPRECATED_` to the name -

```
struct Thing {
  1: i32 id,
  2: string DEPRECATED_phone_number
}
```
This generates a struct with an invalid field name: `defstruct(id: nil, DEPRECATED_phone_number: nil)` which causes the generated file to fail to compile.

**Comment by pguillory** [comment]
Should we just downcase the generated field names? We do that for enums.

**Comment by dantswain** [comment]
I would say `lower_snake_case`.  So `FooBar` => `foo_bar` and `FOO_BAR` => `foo_bar`.
