### ISSUE TITLE
RFC: Generate service handler skeleton

### ISSUE THREAD

**Issue by pguillory** [pinterest/elixir-thrift#179]
For services, the compile.thrift command generates a behavior, then it's up to the user to create a handler module that implements that behavior. It might be useful to have another command that generates a skeleton implementation of such a handler. This would help reduce the friction to get started in situations where the user has an existing thrift and wants to implement a server in Elixir.

### Example
If you had a file:

```thrift
# foo.thrift
namespace GeneratedThriftStuff

service MyService {
  void set(1: binary key, 2: binary value)
  string get(1: binary key)
}
```
You could type:
```bash
mix thrift.skeleton --file foo.thrift --service MyService --name MyServiceHandler
```
And it would write a file:
```elixir
# lib/my_service_handler.ex
defmodule MyServiceHandler do
  @behaviour GeneratedThriftStuff.MyService.Handler

  @spec set(binary, binary) :: :ok
  def set(key, value) do
    raise "Not implemented"
  end

  @spec get(binary) :: binary
  def get(key) do
    raise "Not implemented"
  end
end
```

**Comment by dantswain** [comment]
Maybe obvious, but this would need to have separate output directory control from the thrift-generated code.  This would be a scaffold that you'd build on and check into CMS, vs generally the thrift-generated code would be `.gitignore`d.

**Comment by scohen** [comment]
I like this a lot.

**Comment by pguillory** [comment]
This feels low priority and I don't anticipate that we'll get to it unless we somehow have tons of time, which we will not have. Going to close.
