### ISSUE TITLE
Enum field getting default value when none is set

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#191]
Again I need to come up with an isolated test case or prove to myself that I'm incorrect, but I wanted to document this because I have to switch gears :/  Also this is on `thrift_tng`.

I.e., 
```
enum SomeEnum {
  ONE = 1,
  TWO = 2
}

struct SomeStruct {
  1: optional SomeEnum some_enum
}
```

is giving me

```
defmodule SomeStruct do
  # ...
  defstruct(some_enum: 1)
  # ...
end
```

**Comment by dantswain** [comment]
This is actually already in the first test in generator/models_test.exs

```
  enum Status {
    ACTIVE,
    INACTIVE,
    BANNED = 6,
    EVIL = 0x20,
  }
  struct StructWithEnum {
    1: Status status_field,
    2: map<Status, Status> status_map,
    3: set<Status> status_set,
    4: list<Status> status_list,
  }
```

then

```
    struct = %StructWithEnum{}
    assert struct.status_field == Status.active
```

**Comment by dantswain** [comment]
Oof.  I tried to take a stab at fixing this one.  I was able to get rid of the default value but not able to get it to support default values when they _should_ be set.  I don't fully grok the parser and resolver :/  I'll still poke at it but if someone either has time to give me some Q&A help or just knows how they'd fix this off-hand, that would be fantastic.

**Comment by pguillory** [comment]
Whoops. I specifically remember implementing this with an understanding that the spec dictated it. Nope. No idea where that idea came from, don't see anything about it in the docs.
