### ISSUE TITLE
RFC Allow Keyword lists to serialize into maps

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#192]
This is a selfish request, buuuut I have a situation where I need to serialize a very large map.  I have guarantees on uniqueness from upstream so it would actually be quite a lot more efficient for me to set the field value to a keyword list and let the serializer use that directly rather than doing `kw_list |> Enum.into(%{})` and having the serializer turn that back into a list to enumerate over anyways.

The down sides are a) complexity and b) people could unwittingly break their own stuff if they aren't being careful about uniqueness upstream.

**Comment by jparise** [comment]
We could explore using [annotations](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=blob;f=test/AnnotationTest.thrift;h=06bf57194fc06a6b9eae7138e196bdefca260618;hb=HEAD) for this.

**Comment by pguillory** [comment]
Seems reasonable to me. Worth the complexity.

**Comment by pguillory** [comment]
I went ahead and created a PR, but please consider this RFC still open for discussion if anyone objects to the change.

**Comment by dantswain** [comment]
I think #199 closes this.  We could re-open if anyone is really opposed, but it seems fairly uncontroversial I think?
