### ISSUE TITLE
elixir-thrift's integers are assumed to be unsigned and breaks when negative

### ISSUE THREAD

**Issue by fire** [pinterest/elixir-thrift#206]
thrift's i64 decoding may be broken
 
I get 18446744011573782016 instead of -62135769600

Example code:
```
<micmus> <<int::integer-64-signed>> = :binary.encode_unsigned(18446744011573782016)
<micmus> int => -62135769600
<iFire> iex(44)> DateTime.from_unix(int)
<iFire> {:ok, #<DateTime(0000-12-30T00:00:00Z Etc/UTC)>}
<iFire> \o/
```

This means 16, 32 and 64 signed integers are also broken according to a review of `struct_binary_protocol.ex line 132`.

**Comment by scohen** [comment]
@jparise I'm working on this
