### ISSUE TITLE
Add :ranch_ssl ProtocolHandler support

### ISSUE THREAD

**Issue by jparise** [pinterest/elixir-thrift#214]
Our server-side protocol handler currently only supports `:ranch_tcp`, but the overall interface is capable of supporting other `:ranch_transport`-conforming modules, such as `:ranch_ssl`. Consider implementing support for `:ranch_ssl`, too.

**Comment by bjuretic** [comment]
So currently there is a only a plaintext TCP socket connection between the client and server, and zero security? What are your plans for this in 2.0?

**Comment by fishcakez** [comment]
Currently only support TCP. There are plans to support TLS in 2.0. I don't think we would use a `:ranch_ssl` listener directly but rather upgrade from TCP inside elixir-thrift via a mechanism that allows composing transport (e.g. TLS) and protocol (e.g. THeader) handshake/upgrades.

**Comment by fire** [comment]
I would use a tls version of thrift. 👍
