### ISSUE TITLE
`thrift_test` loses test line numbers

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#229]
I don't know if it's easy to fix this and it shouldn't hold us back I don't think, but I thought I'd make an issue for discussion's sake (maybe someone has an idea for a quick fix).  The `thrift_test` macro makes it impossible to run, e.g., `mix test test/thrift/generator/binary_protocol_test.exs:599` because the line numbers get lost.  Maybe it's as simple as adding `location: :keep` to the `defmacro`?

**Comment by pguillory** [comment]
It's a pretty complex macro. It predates the compile.thrift integration. Would it be possible to convert the thrift_test stuff to simple fixtures now?

**Comment by dantswain** [comment]
> Rule 1: Don't Write Macros
 - Metaprogramming Elixir, Chris McCord

I think I would prefer that.  Every time I've tried to use macros to automate tests, it's come back to bite me eventually :/   It would be a fairly large undertaking to convert everything, though :(

One compromise might be to change the macro so that it's intended to be used either as an annotation or inside the test case - i.e., either

```
@thrift_test "idunno what would go here"
test "the test case" do
  # test assertions
end
```

or

```
test "the test case" do
  @thrift_test "idunno what would go here"
  # test assertions
end
```

Or better yet, if it could all just be put in the setup/setup_all blocks somehow and anything specific to a particular test could just be a function call?

**Comment by jparise** [comment]
I would also like us to rely less on disk-based file generation where possible. We should be able to write the majority of our tests in terms of in-memory, AST-based assertions.

**Comment by dantswain** [comment]
It would be really handy if there was still an option to write the generated code to disk - I've found that to be super handy for debugging.

**Comment by scohen** [comment]
My $0.02: When debugging, I've found it incredibly helpful to have a file with the generated code out there.  
We should not conflate the macros being difficult to debug with having artifacts on disk.

If I were to re-do this, I'd leverage describe blocks and setup functions. It would be cool to do:

```lang-elixir
thrift_file "filename.thrift",  contents: """
 // thrift contents
"""

describe "using filenae.thrift" do 
  setup :generate_filename 

  test "doing something"  do 
    # in here, you have everything inside of the above thrift file
  end 
```

Basically, the thrift_file function builds a function that can be used in a setup callback in a describe block. It'd also generate `on_exit` teardown fns.

**Comment by jparise** [comment]
I'm fine with there being an _option_ to write the generated files to disk, but I don't like the fact that so many of our tests are dependent upon disk-based code generation. (The mix and generator tests are an obviously exception.)

**Comment by scohen** [comment]
@jparise can you clarify why you have this objection? Of all the things, it doesn't seem like it's causing problems.

**Comment by scohen** [comment]
@jparise I'm fine with an option too, as it's similar to what we have now (our option doesn't _clean up_ the files).

**Comment by fishcakez** [comment]
I have picked up this issue. I just have a problem with containers.
