### ISSUE TITLE
Typedefs and Enums not resolved by parser

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#23]
This might not be an actual issue, but I wanted to document it just in case.

It appears that when `Thrift.Parser.parse/1` comes across a typedef or enum field, it treats that as a `Thrift.Parser.Models.StructRef`.  In retrospect this is probably because the parser doesn't know about other modules, so it can't do any better than to say it must be a reference to some other type.  Having "Struct" in the name threw me off at first, I think.

Here's an example thrift IDL file: 

<script src="https://gist.github.com/dantswain/623215759d3413a1a6b7e68b37b039f8.js"></script>

When I parse that, the typedefed field and the enum field come out as StructRefs:

```
iex(4)> Enum.at(idl.structs[:SimpleStruct].fields, 3)
%Thrift.Parser.Models.Field{default: nil, id: 4, name: :bigint,
 required: :default,
 type: %Thrift.Parser.Models.StructRef{referenced_type: :UgeInt}}

iex(5)> Enum.at(idl.structs[:SimpleStruct].fields, 7)
%Thrift.Parser.Models.Field{default: nil, id: 8, name: :taco_pref,
 required: :default,
 type: %Thrift.Parser.Models.StructRef{referenced_type: :TacoType}}
```

I'm writing some code for thrash that will parse a collection of idl files and return a merged IDL.  I think to really determine the types for those fields I'm going to have to resolve the references myself?  If that code could be useful here I could make it something that would be easy to migrate.

**Comment by dantswain** [comment]
Should I close this or is it still WIP?

**Comment by pguillory** [comment]
I think the name resolution in FileGroup does what you need. Please re-open if I misunderstood.
