### ISSUE TITLE
Support ThriftMux

### ISSUE THREAD

**Issue by pguillory** [pinterest/elixir-thrift#256]
https://twitter.github.io/finagle/guide/Protocols.html#mux

We're gradually switching internal services from binary protocol to mux. I'm going to explore adding support. The above link points to the Finagle source as a reference implementation. We also have an internal implementation in Python that I'll work from.  Does anyone know of any other good resources?

**Comment by scohen** [comment]
@pguillory There are zero resources for tmux other than the linked-to source. Our python version is probably 100x better.

**Comment by pguillory** [comment]
Going to close this. I'm not actually finding the time to work on it and I don't want anyone else to feel blocked from doing so.

**Comment by fishcakez** [comment]
I have a branch at https://github.com/fishcakez/elixir-thrift/tree/thrift_mux that can speak a flavour of mux, and communicate with thrift over mux with itself.
