### ISSUE TITLE
Review binary framed client TCP error handling

### ISSUE THREAD

**Issue by fishcakez** [pinterest/elixir-thrift#261]
Regarding this error handling: https://github.com/pinterest/elixir-thrift/blob/1168b29d4099045fb788f489472cf56fa75ca962/lib/thrift/binary/framed/client.ex#L229-L236

I believe that a timeout will cause the client to get out of sync and can only ever return an prior sequence id - if it does not keep timing out. This occurs because the next `call` will receive the result of the prior call - if it receives anything. This can continue forever with no hope of recovery.

I have not tried this but it appears that by returning an error atom on tcp error it will try to raise an atom later on https://github.com/pinterest/elixir-thrift/blob/1168b29d4099045fb788f489472cf56fa75ca962/lib/thrift/generator/binary/framed/client.ex#L85, which will fail. Should that use `:inet.format_error/1` on the `:inet` error atom to raise a RuntimeError or create a custom exception?

**Comment by fishcakez** [comment]
We need to introduce a custom exception, something like `ThriftConnectionError` to handle the connection errors: https://github.com/pinterest/elixir-thrift/blob/89130e838a70d7f1fb68e7da3b9b25acb6ac86af/lib/thrift/generator/binary/framed/client.ex#L85-L86 If we use the bang variants then this will fail with an argument error because we are attempting to raise `{:error, atom}`. Instead it should be something like:
```elixir
{:error, reason} ->
  raise ThriftConnectionError, reason: reason
```

The `reason` can also be `:timeout`: https://github.com/pinterest/elixir-thrift/blob/89130e838a70d7f1fb68e7da3b9b25acb6ac86af/lib/thrift/binary/framed/client.ex#L252-L253 In this situation we also want to close the socket because its possible for the following infinite loop of errors to occur:

1. Send call with seq id X.
2. Timeout receiving the response for call with seq id X.
3. Send call with seq id X + 1.
4. Receive response for seq id X when expecting X + 1, therefore raise `TApplicationException`.
5. Send call with seq id X + 2.
6. Receive response for seq id X + 1 when expecting X + 2, therefore raise `TApplicationException`.

It might even be that 4. or 6. etc will also timeout because the server likely blocks until the prior the call finishes. Therefore X+1 has to wait for X to finish before it is started, and is then much more likely to also timeout.

Likely we also want to have a different exception for a timeout as a user may want to handle `:timeout`, differently to a connection error, perhaps `ThriftTimeoutError`.

**Comment by jparise** [comment]
@fishcakez, is there anything else you think we should cover under the issue?

**Comment by fishcakez** [comment]
This looks good.
