### ISSUE TITLE
UDP support for server? 

### ISSUE THREAD

**Issue by seivan** [pinterest/elixir-thrift#332]
Do you guys have any plans or reservation on adding UDP support to the server? 
I assume some changes would have to go into [Riffed](https://github.com/pinterest/riffed) as well.

**Comment by fishcakez** [comment]
@seivan I'm not aware of a UDP transport for Thrift RPC, or at least a commonly used one. We don't have any plans. Some work would need to be done to generalize transports/protocols, likely this might need to be done anyway. Do you have an example?

**Comment by seivan** [comment]
Oh hey it's @fishcakez !

Yeah I am not aware if the standards for Thrift RPC is meant to support UDP or if it's compatible at all, in which case this ticket can be closed, but I saw http://gruchalski.com/apache-thrift-via-udp-in-erlang.html and thought I would use an RPC instead of just dealing with UDP and converting binaries myself.

**Comment by jparise** [comment]
Right, there's no standard UDP transport for Thrift RPC, but you can certainly ship Thrift-encoded binary data over any transport you like. The linked post shows a custom UDP-based implementation.

As @fishcakez notes, this would be possible to add to elixir-thrift, but we have no plans to develop this support ourselves. You could build upon the serialization capabilities of this library to build something yourself however.
