### ISSUE TITLE
Sharing modules across apps

### ISSUE THREAD

**Issue by sarat1669** [pinterest/elixir-thrift#547]
I want to invoke the service using the generated client in a different elixir service.
What are the common/best practices to achieve this?

**Comment by jparise** [comment]
One approach is to use an umbrella application where one of the (sub)applications is dedicated to just the generated Thrift code. Then, other applications can depend on that code (either as clients or servers).

**Comment by sarat1669** [comment]
@jparise , I was doing something similar

```
  {:base, path: "../light_base"}
```

But I am a bit worried about this appoach as well.

My application name is `Light`
The generated modules are `Light.Base.*`
If we move it to a different application, the module names have to be different ex: `LightBase`
Keeping it as `Light.Base` in a different application seems like an antipattern.

**Comment by jparise** [comment]
In our case, we used a different namespace for the generated Thrift modules (e.g. `LightThrift` or `LightGen`).

**Comment by sarat1669** [comment]
Oh okay. I guess I will do something on the similar lines then.
Thanks for the info
