### ISSUE TITLE
Better default namespaces

### ISSUE THREAD

**Issue by scohen** [pinterest/elixir-thrift#57]
If you don't specify an elixir namespace, the generator puts files into the root namespace. This is troublesome, as different thrift modules can specify the same name for a struct / union / enum. 

If no namespace is specified, we should use the thrift namespace as a default.

**Comment by dantswain** [comment]
@scohen can you clarify what you mean by "the thrift namespace"?  Do you mean, literally, "Thrift" or whatever namespace is specified in the IDL file?

**Comment by pguillory** [comment]
Tried it on some of the other generators (cpp, java, php) and found that they put things in the root namespace if there is no 'namespace' annotation for the given language. I think we should stick with that behavior.

**Comment by scohen** [comment]
@pguillory, but in our instance, that implementation is _broken_. If you put them in the root namespace, one version will overwrite the other.

**Comment by pguillory** [comment]
What's the current thinking on this? We're adding `elixir` namespaces to our schemas?

**Comment by scohen** [comment]
I'm still of the opinion that not having a namespace shouldn't break things. 

Imagine this scenario:
I have two files `service_1.thrift` and `service_2.thrift`.
They both have a struct `RequestContext`.

The last one that compiles wins. There can be only one request_context.ex. Now the service defined by `service_1.thrift` is broken. 

The thing is, all of the other thrift generators will give you a default namespace of `service_1` and `service_2`, so they won't have this problem. 

It's worth noting that this is not a hypothetical problem.

**Comment by scohen** [comment]
I'm also finding myself going through our source code and adding 
```
namespace elixir Maia
```
in a file called `maia.thrift`.

**Comment by jparise** [comment]
Another approach would be **requiring** the `elixir` namespace to be present in all schema files. I don't think that's the right solution, but I wanted to mention it here for completeness.

**Comment by pguillory** [comment]
Here's what some of the other generators are doing when you don't specify a namespace.

- cpp: root namespace
- erl: creates a module, seems to ignore namespaces completely
- go: creates a package
- java: root namespace
- js: root namespace
- php: root namespace
- py: creates a module, i.e. file
- rb: root namespace

What we're doing at the moment is actually very similar to the Java generator, which generates a file per class. It overwrites the generated file if different thrift files use the same type name.

**Comment by jparise** [comment]
We could continue with our current (Java-like) behavior but also emit a warning about using the default root namespace.

**Comment by scohen** [comment]
I just don't see why the Java behavior is desirable at all.  It produces broken code. Worse, that code will fail at runtime, when the message is deserialized by the server or client, yielding a confusing and unhelpful TApplicationException. 

I get why erlang does what it does, since it doesn't really have the concept of nested modules. Fun fact, I added erl namespaces in the as yet unreleased 0.10 which is why @pguillory doesn't see them. 

I also don't see a reason for not using the file name as a default. That's consistent with how you reference entities in thrift and will always produce working code. 
So far, I have yet to see an argument against this behavior other than "other implementations do it that way", which imo isn't much of an argument. 

I'd be more ok if we detected a file being overwritten and failed hard, but that's worse than producing working code by default.

**Comment by scohen** [comment]
Ok. It won't always produce working code. If you have 
/foo/bar.thrift
/baz/bar.thrift

And neither have a namespace, it'll fail.

**Comment by scohen** [comment]
I also stand corrected. 0.10 was released Tuesday.

**Comment by dantswain** [comment]
It seems like it's within our parser's capabilities to detect that a symbol (struct/const/whatever) is being defined multiple times.  I think it would make sense to fail on _that_ rather than fail on overwriting a file, since overwriting a file is going to happen every time someone compiles.

**Comment by pguillory** [comment]
Yeah we should try to detect the collision itself. @jparise has the other project around storing metadata about generated files. What if we stored the path to the original .thrift file in that metadata. If it gets regenerated from the same .thrift file, that's fine, you're just recompiling. If it gets regenerated from a different .thrift file, we flag that as a probable namespace collision.

Also we should catch name collisions within the same file. Got bit by that yesterday. :/ But we can do that entirely in the resolver.

**Comment by scohen** [comment]
So, we ran into another issue today, one of our Thrift files defines a `Node` struct, and we plunk it in the default namespace, which means that it conflicts with the stdlib `Node` module. 

This means we not only have to detect collisions between defined thrift files, but we have to detect collisions with all _loaded_ modules. 

I really think we should reevaluate the decision here.

**Comment by jparise** [comment]
I agree that we should never write files to the "root" namespace. That gives us two options:

1. Prefix all generated files with a static namespace (like `Thrift.Generated`) and append any custom namespace bits to the end of that.
2. Default to something like `Thrift.Generated` but allow custom namespaces to override it entirely.

(2) seems like the friendliest way forward.

**Comment by dantswain** [comment]
It seems to me like this is just rope that a user is free to hang themselves with.  There's no way to know that a user won't clobber their own code or the namespace from some third party dependency. As long as our documentation makes the rules clear, it's really on the user to be responsible for this. There's nothing stopping a user from straight-up doing defmodule Node.

**Comment by scohen** [comment]
@dantswain  Other than the VM not starting?

**Comment by scohen** [comment]
@dantswain I'm actually pretty curious as to why this is so controversial; Wouldn't it be better to have a reasonable default that you can override? Something like: By default, generate in Thrift.Generated, but you can override to another module, or if you want the root Module. 

I think we should start with the gun pointed away from the user's foot.  If the user wants to point it at their foot, so be it, but it doesn't have to be the default.

**Comment by dantswain** [comment]
"Controversial" is a stronger word than I'd use :P  I think a default is probably fine (as you said: it points the gun away from the foot), but I still think `nil` (write to root namespace) _should_ be an option in an ideal world.

* Disallowing the root namespace takes away an entire dimension from the domain of outputs.  That tickles my "this is gonna bite you in the butt some day"-spidey-sense.

* Adding code to disallow the root namespace doesn't guarantee that someone won't introduce a collision anyways.  Even in the stdlib there are namespaced modules.

* Any kind of collision cop or validation adds code which in turn adds complexity.

I think defaulting to something like `Thrift.Generated` is fine, though.
