### ISSUE TITLE
Better interface for decode

### ISSUE THREAD

**Issue by scohen** [pinterest/elixir-thrift#58]
On success, decode returns a tuple with the decoded entity and an empty string. Instead, it would be nice if it did something like:
```elixir
case MyThriftStruct.BinaryProtocol.decode(binary_data) do 
  {:ok, %MyThriftStruct{}=s} -> 
       s
   {:more, %MyThriftStruct{}=s, extra_data} ->
      ...
   {:error, reason} ->
      ...
end
```

**Comment by pguillory** [comment]
I think it's straightforward to match away the leftover "". It's a common enough pattern in Elixir.
```elixir
iex(1)> Integer.parse("123")
{123, ""}
```

**Comment by scohen** [comment]
I disagree, from a user's perspective it's unnecessary in most cases and cumbersome, which might be why I don't use Integer.parse.
```elixir
iex(2)> String.to_integer("123")
123
```

**Comment by scohen** [comment]
Also, ignore my suggestion; feel free to implement it in other ways.

**Comment by dantswain** [comment]
I'm with @pguillory on this - returning `{value, remainder}` or `:error` is how the various `.parse` functions work.  You could also supply a banged `decode!` function that returns the value on success and raises on failure.

**Comment by scohen** [comment]
alright.
